#+OPTIONS: \n:nil toc:nil num:nil html-postamble:nil
#+PROPERTY: header-args:shell :prologue "exec 2>&1" :epilogue ":" :results drawer :async
* ZMK Config

My personal ZMK CONFIG's for my keyboards.

** Docker:

Distilled from: [[https://zmk.dev/docs/development/setup][ZMK Docs: Toolchain Setup]] and [[https://zmk.dev/docs/development/build-flash][ZMK Docs: Building and Flashing]].

- Get ZMK source to mount into container: ~git clone
  https://github.com/zmkfirmware/zmk.git~.
- Initialise a Docker Container that will be modified: ~docker run -it --name
  zmk -v $HOME/github_repos/zmk/app/:/app -v
  $HOME/github_repos/zmk-config:/zmk-config zmkfirmware/zmk-build-arm:stable~.
- ~docker stop zmk~.
- ~docker sart zmk~.
  - Initial setup in the container:
    - ~west init -l /app~
    - ~west update~
    - ~west zephyr-export~
  - Subsequent builds in the container:
    - ~cd /app~
    - ~west build -p -d build/cradio/right/ --board nice_nano -- -DSHIELD=cradio_right -DZMK_CONFIG=/zmk-config/config && west build -p -d build/cradio/left/ --board nice_nano -- -DSHIELD=cradio_left -DZMK_CONFIG=/zmk-config/config && west build -p -d build/ferris --board ferris_rev02 -- -DZMK_CONFIG=/zmk-config/config~

*** Org codeblock to initialise the =zmk= docker container:

#+BEGIN_SRC shell :var zmk_path="../zmk"
  echo "- Get ZMK source to mount into container..."
  git clone https://github.com/zmkfirmware/zmk.git $zmk_path || true
  cd $zmk_path
  git pull
  cd -

  echo "- Initialise a Docker Container that will be modified..."
  docker run --name zmk -v $PWD/$zmk_path/app/:/app -v $PWD:/zmk-config zmkfirmware/zmk-build-arm:stable sleep infinity

  docker stop zmk
  docker start zmk

  echo "- Initial setup in the container..."
  docker exec zmk west init -l /app
  docker exec zmk west update
  docker exec zmk west zephyr-export
#+END_SRC

*** Org codeblock to build firmware's in the =zmk= docker container:

#+BEGIN_SRC shell :var zmk_path="../zmk"
  echo "- Subsequent builds in the container..."
  docker exec zmk west build -p -s /app -d build/cradio/right/ --board nice_nano -- -DSHIELD=cradio_right -DZMK_CONFIG=/zmk-config/config
  docker exec zmk west build -p -s /app -d build/cradio/left/ --board nice_nano -- -DSHIELD=cradio_left -DZMK_CONFIG=/zmk-config/config
  docker exec zmk west build -p -s /app -d build/ferris --board ferris_rev02 -- -DZMK_CONFIG=/zmk-config/config
#+END_SRC

** flashing:

Pre-reqs:

- Connect usb.
- Quickly double tap reset button or =GND= + =RST= pins.

USB Storage devices (eg. nice!nano):

- Mac doesn't auto-mount FAT16 external drives. Therefore:
  - ~sudo mount -t msdos /dev/disk<#> </mount/path>~

  #+BEGIN_SRC shell :var zmk_path="../zmk"
    echo "- Double-tap GND & RST now!!"
    mkdir -p ~/Downloads/mounted_keyboard
    echo "- NOTE: hardcoding to /dev/disk4 for my mac."
    sleep 10; ls -al /dev/disk*; sudo mount -t msdos /dev/disk4 Downloads/mounted_keyboard
    echo "- Copy .uf2 file to mounted Nice!Nano now."
  #+END_SRC

- All:
  - ~cp </path/to/build/<shield>/<side>/zephyr/zmk.uf2> </mount/path>~.
  - Unplug after device unmounts itself.
  - Power cycle board.
