* ZMK Config

My personal ZMK CONFIG's for my keyboards.

** Docker:

Distilled from: [[https://zmk.dev/docs/development/setup][ZMK Docs: Toolchain Setup]] and [[https://zmk.dev/docs/development/build-flash][ZMK Docs: Building and Flashing]].

- Get ZMK source to mount into container: ~git clone
  https://github.com/zmkfirmware/zmk.git~.
- Initialise a Docker Container that will be modified: ~docker run -it --name
  zmk -v $HOME/github_repos/zmk/app/:/app -v
  $HOME/github_repos/zmk-config:/zmk-config zmkfirmware/zmk-build-arm:stable~.
- ~docker stop zmk~.
- ~docker sart zmk~.
  - Initial setup in the container:
    - ~west init -l /app~
    - ~west update~
    - ~west zephyr-export~
  - Subsequent builds in the container:
    - ~cd /app~
    - ~west build -p -d build/cradio/right/ --board nice_nano -- -DSHIELD=cradio_right -DZMK_CONFIG=/zmk-config/config && west build -p -d build/cradio/left/ --board nice_nano -- -DSHIELD=cradio_left -DZMK_CONFIG=/zmk-config/config && west build -p -d build/ferris --board ferris_rev02 -- -DZMK_CONFIG=/zmk-config/config~

** flashing:

Pre-reqs:

- Connect usb.
- Quickly double tap reset button or =GND= + =RST= pins.

USB Storage devices (eg. nice!nano):

- Mac doesn't auto-mount FAT16 external drives. Therefore:
  - ~sudo mount -t msdos /dev/disk<#> </mount/path>~
- All:
  - ~cp </path/to/build/<shield>/<side>/zephyr/zmk.uf2> </mount/path>~.
  - Unplug after device unmounts itself.
  - Power cycle board.
